src/Entity/Document.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DocumentRepository")
 * @Vich\Uploadable
 * @UniqueEntity(
 *     fields={"discipline", "building", "version", "documentType"},
 *     errorPath="location",
 *     message="Een document met deze bestandsnaam bestaat al"
 * )
 * UNIQUE ENTITY NEEMT FLOOR NIET IN BESCHOUWING. DIT IS EEN BUG IN SYMFONY. UNIQUEENTITY TRIGGERT NIET OP NULL VALUES.
 */
class Document
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     * @var string
     */
    private $file_name;

    /**
     * @Vich\UploadableField(mapping="documents", fileNameProperty="file_name")
     */
    private $file_content;

    /**
     * @Vich\UploadableField(mapping="pdf", fileNameProperty="pdf_filename")
     */
    private $pdf_file;

    /**
     * @ORM\Column(type="string", length=100)
     * @var string
     */
    private $pdf_filename;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Discipline", inversedBy="documents", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $discipline;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Area", inversedBy="documents")
     */
    private $area;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Building", inversedBy="documents")
     */
    private $building;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Location", inversedBy="documents")
     */
    private $location;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $floor;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\DocumentHistory", mappedBy="document")
     * @ORM\OrderBy({"revision" = "DESC"})
     */
    private $documentHistories;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\DocumentType", inversedBy="documents")
     * @ORM\JoinColumn(nullable=false)
     */
    private $documentType;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Issue", mappedBy="document", cascade={"persist", "remove"})
     */
    private $issue;

    /**
     * @ORM\Column(type="integer", nullable=false)
     */
    private $version;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\DocumentDraft", mappedBy="document")
     */
    private $documentDrafts;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     */
    private $uploadedBy;


    public function __construct()
    {
        $this->documentHistories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFileName(): ?string
    {
        return $this->file_name;
    }

    /**
     * Return filename without file extension
     * @return string
     */
    public function getDocumentName(): string
    {
        return substr($this->file_name, 0, -4);
    }

    public function setFileName(?string $file_name): self
    {
        $this->file_name = $file_name;

        return $this;
    }

    public function getPdfFilename()
    {
        return $this->pdf_filename;
    }

    public function setPdfFilename(?string $name)
    {
        $this->pdf_filename = $name;

        return $this;
    }

    public function getFileContent()
    {
        return $this->file_content;
    }

    public function setFileContent($file_content = null): void
    {
        $this->file_content = $file_content;

        if ($file_content) {
            $this->updated_at = new \DateTime('now');
        }
    }

    public function getPdfFile()
    {
        return $this->pdf_file;
    }

    public function setPdfFile($pdf_file = null): void
    {
        $this->pdf_file = $pdf_file;

        if ($pdf_file) {
            $this->updated_at = new \DateTime('now');
        }
    }

    public function getFloor(): ?string
    {
        return $this->floor;
    }

    public function setFloor(?string $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getDisciplineCode(): ?discipline
    {
        return $this->discipline;
    }

    public function setDisciplineCode(?discipline $discipline_code): self
    {
        $this->discipline = $discipline_code;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDiscipline(): ?Discipline
    {
        return $this->discipline;
    }

    public function setDiscipline(?Discipline $discipline): self
    {
        $this->discipline = $discipline;

        return $this;
    }

    /** Files only contain .pdf or .dwg, so slice last four characters */
    public function getFileType()
    {
        return substr($this->file_name, -4, 4);
    }

    public function __toString()
    {
        return $this->getFileName();
    }

    public function getArea(): ?Area
    {
        return $this->area;
    }

    public function setArea(?Area $area): self
    {
        $this->area = $area;

        return $this;
    }

    public function getBuilding(): ?Building
    {
        return $this->building;
    }

    public function setBuilding(?Building $building): self
    {
        $this->building = $building;

        return $this;
    }

    public function getLocation(): ?Location
    {
        return $this->location;
    }

    public function setLocation(?Location $location): self
    {
        $this->location = $location;

        return $this;
    }

    /**
     * @return Collection|DocumentHistory[]
     */
    public function getDocumentHistories(): Collection
    {
        return $this->documentHistories;
    }

    public function addDocumentHistory(DocumentHistory $documentHistory): self
    {
        if (!$this->documentHistories->contains($documentHistory)) {
            $this->documentHistories[] = $documentHistory;
            $documentHistory->setDocument($this);
        }

        return $this;
    }

    public function removeDocumentHistory(DocumentHistory $documentHistory): self
    {
        if ($this->documentHistories->contains($documentHistory)) {
            $this->documentHistories->removeElement($documentHistory);
            // set the owning side to null (unless already changed)
            if ($documentHistory->getDocument() === $this) {
                $documentHistory->setDocument(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|DocumentDraft[]
     */
    public function getDocumentDrafts(): Collection
    {
        return $this->documentDrafts;
    }

    public function addDocumentDrafts(DocumentDraft $documentDraft): self
    {
        if (!$this->documentDrafts->contains($documentDraft)) {
            $this->documentDrafts[] = $documentDraft;
            $documentDraft->setDocument($this);
        }

        return $this;
    }

    public function removeDocumentDrafts(DocumentDraft $documentDraft): self
    {
        if ($this->documentDrafts->contains($documentDraft)) {
            $this->documentDrafts->removeElement($documentDraft);
            // set the owning side to null (unless already changed)
            if ($documentDraft->getDocument() === $this) {
                $documentDraft->setDocument(null);
            }
        }

        return $this;
    }

    public function getDocumentType(): ?DocumentType
    {
        return $this->documentType;
    }

    public function setDocumentType(?DocumentType $documentType): self
    {
        $this->documentType = $documentType;

        return $this;
    }

    public function getIssue(): ?Issue
    {
        return $this->issue;
    }

    public function setIssue(Issue $issue): self
    {
        $this->issue = $issue;

        // set the owning side of the relation if necessary
        if ($issue->getDocument() !== $this) {
            $issue->setDocument($this);
        }

        return $this;
    }

    /**
     * @return integer
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * @param integer $version
     */
    public function setVersion($version): void
    {
        $this->version = $version;
    }

    public function getUploadedBy(): ?User
    {
        return $this->uploadedBy;
    }

    public function setUploadedBy(?User $uploadedBy): self
    {
        $this->uploadedBy = $uploadedBy;

        return $this;
    }
}

src/Entity/DocumentHistory.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DocumentHistoryRepository")
 * @Vich\Uploadable
 */
class DocumentHistory
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="string", length=100)
     * @var string
     */
    private $file_name;

    /**
     * @Vich\UploadableField(mapping="documents", fileNameProperty="file_name")
     */
    private $file_content;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $revision_description;

    /**
     * @ORM\Column(type="integer")
     */
    private $revision;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=true)
     */
    private $updated_by;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Document", inversedBy="documentHistories")
     */
    private $document;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $pdf_filename;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function getFileName(): ?string
    {
        return $this->file_name;
    }

    public function setFileName(?string $file_name): self
    {
        $this->file_name = $file_name;

        return $this;
    }

    public function getFileContent()
    {
        return $this->file_content;
    }

    public function setFileContent($file_content = null): void
    {
        $this->file_content = $file_content;

        if ($file_content) {
            $this->updated_at = new \DateTime('now');
        }
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getRevisionDescription(): ?string
    {
        return $this->revision_description;
    }

    public function setRevisionDescription(?string $revision_description): self
    {
        $this->revision_description = $revision_description;

        return $this;
    }

    public function getRevision(): ?int
    {
        return $this->revision;
    }

    public function setRevision(int $revision): self
    {
        $this->revision = $revision;

        return $this;
    }

    public function getUpdatedBy(): ?user
    {
        return $this->updated_by;
    }

    public function setUpdatedBy(?user $updated_by): self
    {
        $this->updated_by = $updated_by;

        return $this;
    }

    public function getDocument(): ?Document
    {
        return $this->document;
    }

    public function setDocument(?Document $document): self
    {
        $this->document = $document;

        return $this;
    }

    public function getPdfFilename(): ?string
    {
        return $this->pdf_filename;
    }

    public function setPdfFilename(string $pdf_filename): self
    {
        $this->pdf_filename = $pdf_filename;

        return $this;
    }
}

src/Entity/DocumentType.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DocumentTypeRepository")
 */
class DocumentType
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Document", mappedBy="documentType")
     */
    private $documents;

    public function __construct()
    {
        $this->documents = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCode(): ?int
    {
        return $this->code;
    }

    public function setCode(int $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Document[]
     */
    public function getDocuments(): Collection
    {
        return $this->documents;
    }

    public function addDocument(Document $document): self
    {
        if (!$this->documents->contains($document)) {
            $this->documents[] = $document;
            $document->setDocumentType($this);
        }

        return $this;
    }

    public function removeDocument(Document $document): self
    {
        if ($this->documents->contains($document)) {
            $this->documents->removeElement($document);
            // set the owning side to null (unless already changed)
            if ($document->getDocumentType() === $this) {
                $document->setDocumentType(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getCode() . ": ". $this->getName();
    }
}

src/Form/DocumentType.php
<?php

namespace App\Form;

use App\Entity\Area;
use App\Entity\Building;
use App\Entity\Discipline;
use App\Entity\Location;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class DocumentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add("fileContent", FileType::class)
            ->add("location", EntityType::class, [
                'class' => Location::class
            ])
            ->add("building", EntityType::class, [
                'class' => Building::class
            ])
            ->add("floor", TextType::class)
            ->add("area", EntityType::class, [
                'class' => Area::class
                ])
            ->add("discipline", EntityType::class, [
                'class' => Discipline::class
            ])
            ->add("documentType", EntityType::class, [
                'class' => \App\Entity\DocumentType::class
            ])
            ->add("description", TextareaType::class)
            ->add("submit", SubmitType::class)
        ;
    }
}

templates/documents/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% include 'partials/navbar.html.twig' %}
    <div class="container">
        <div class="col-md-12">
            <ol class="breadcrumb shadow-sm bg-white">
                <li class="breadcrumb-item"><a href="{{ path('home') }}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{ path('documents.index') }}">documenten</a></li>
                <li class="breadcrumb-item active">{{ document.documentName }}</li>
            </ol>
        </div>
        {%  include 'partials/flashbag.html.twig' %}
        <div class="row">
            <div class="col-md-6">
                <div id="pdfContainer" class="col-md-12 no-padding">
                    <embed src="{{ asset('pdf/' ~ document.pdfFileName) }}" width="100%" height="100%" >
                </div>
            </div>
            <div class=" col-md-6">
                <div id="detailsContainer" class="card">
                    <div id="specificationContainer">
                        <div class="card_head">
                            <h4>Specificaties</h4>
                        </div>
                        <div class="card_body">
                            <p>
                                {{ document.description }}
                            </p>
                        </div>
                        <div class="no-padding">
                            <table class="table align table-striped">
                                <tbody>
                                <tr>
                                    <td>Naam</td>
                                    <td>{{ document.documentName }}</td>
                                </tr>
                                <tr>
                                    <td>Discipline</td>
                                    <td>{{ document.discipline }}</td>
                                </tr>
                                <tr>
                                    <td>Revisie #</td>
                                    <td>{{ document.version }}</td>
                                </tr>
                                <tr>
                                    <td>Laatst geupdate</td>
                                    <td>{{ document.updatedAt.format("d-m-Y") }}</td>
                                </tr>
                                <tr>
                                    <td>Organisatie</td>
                                    <td>{{ document.location.organisation }}</td>
                                </tr>
                                <tr>
                                    <td>Locatie</td>
                                    <td>{{ document.location }}</td>
                                </tr>
                                <tr>
                                    <td>Gebouw</td>
                                    <td>{{ document.building ? document.building : "N.V.T." }}</td>
                                </tr>
                                <tr>
                                    <td>Gebouwdeel</td>
                                    <td>{{ document.area ? document.area : "N.V.T." }}</td>
                                </tr>
                                <tr>
                                    <td>Verdieping</td>
                                    <td>{{ document.floor is not empty ? document.floor : "N.V.T." }}</td>
                                </tr>
                                <tr>
                                    <td>Document type</td>
                                    <td>{{ document.documentType ? document.documentType : "N.V.T." }}</td>
                                </tr>

                                </tbody>
                            </table>
                        </div>
                    </div>
                    <hr>
                    <div id="buttonContainer" class="p-3 pt-0!">
                        <button type="button" class="btn d-inline-block btn-info" data-toggle="modal" data-target="#requestPdf">PDF downloaden</button>
                        {# Alleen leveranciers en + mogen revisie doen#}
                        {% if is_granted("ROLE_LEVERANCIER") %}
                            <button type="button" class="btn d-inline-block btn-info" data-toggle="modal" data-target="#requestDwg1">DWG downloaden</button>
                        {% else %}
                            <a class="closemodal" href="{{ path('document.download', {documentId: document.id, type: "DWG", issue: false}) }}">
                                <button type="button" class="btn btn-info">DWG downloaden</button>
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6 offset-6 mt-3">
            <div class="card">
                <div >
                    <div class="card_head">
                        <h4>Geschiedenis</h4>
                    </div>
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Versie</th>
                            <th>Geupload op</th>
                            <th>Door</th>
                            <th>Acties</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>{{ document.version }}</td>
                            <td>{{ document.updatedAt.format("d-m-Y") }}</td>
                            <td>{{ document.uploadedBy }}</td>
                            <td>
                                <a class="closemodal"
                                   href="{{ path('document.download', {documentId: document.id, type: "DWG", issue: false}) }}">
                                    DWG
                                </a>
                                <a class="closemodal"
                                   href="{{ path('document.download', {documentId: document.id, type: "PDF", issue: false}) }}">
                                    PDF
                                </a>
                            </td>
                        </tr>
                        {% if documentHistory is defined %}
                            {% for history in documentHistory %}
                                <tr>
                                    <td>{{ history.revision }}</td>
                                    <td>{{ history.updatedAt.format("d-m-Y") }}</td>
                                    <td>{{ history.updatedBy }}</td>
                                    <td>
                                        <a class="closemodal"
                                           href="{{ path('document.download.revision', {revisionId: history.id, fileType: "dwg"}) }}">
                                            DWG
                                        </a>
                                        <a class="closemodal"
                                           href="{{ path('document.download.revision', {revisionId: history.id, fileType: "pdf"}) }}">
                                            PDF
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    {#  PDF Opvragen modal  #}
    <div class="modal fade" id="requestPdf" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">PDF opvragen</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Aan deze actie zijn kosten verbonden. Wilt u doorgaan?
                </div>
                <div class="modal-footer">
                    <a href="{{ path('document.download', {documentId: document.id, type: "PDF", issue: false}) }}">
                        <button type="button" class="btn btn-info closeModal">Doorgaan</button>
                    </a>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Sluiten</button>
                </div>
            </div>
        </div>
    </div>

    {#  DWG Opvragen modal  #}
    <div class="modal fade" id="requestDwg1" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">DWG opvragen 1/2</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <span class="small_bold">Bent u van plan dit document te updaten en uploaden?</span>
                    <br>
                    <ul>
                        <li><span class="small_bold">Ja</span> Het document gaat in revisie en u dient de nieuwe revisie binnen de afgesproken tijd in te leveren.</li>
                        <li><span class="small_bold">Nee</span> U kunt de DWG downloaden voor eigen gebruik.</li>
                    </ul>

                    <br>

                </div>
                <div class="modal-footer">
                    {% if canDoRevision %}
                        <button type="button" class="btn btn-info btn-next">Met revisie</button>
                    {% else %}
                        <span class="d-inline-block" tabindex="0" data-toggle="tooltip" data-placement="bottom" title="Dit document is momenteel in revisie en kan pas opnieuw aangevraagd worden als dit is afgerond.">
                            <button disabled style="pointer-events: none;" type="button" class="btn btn-info">Met revisie</button>
                        </span>
                    {% endif %}
                    <a class="closemodal" href="{{ path('document.download', {documentId: document.id, type: "DWG", issue: false}) }}">
                        <button type="button" class="btn btn-info closeModal">Zonder revisie</button>
                    </a>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Sluiten</button>
                </div>
            </div>
        </div>
    </div>

    {# Inleverdatum modal #}
    <div class="modal fade" id="requestDwg2" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <form action="{{ path('document.download', {documentId: document.id, type: "DWG", issue: true}) }}">
                    <div class="modal-header">
                        <h5 class="modal-title">DWG opvragen 2/2</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>Wanneer wordt de revisie uiterlijk opgeleverd?</p>
                        <label>
                            Datum: <input type="date" name="deadlineInput" value="{{ defaultDeadlineDate.format("Y-m-d") }}" min="{{ minDeadlineDate.format('Y-m-d') }}" max="{{ maxDeadlineDate.format('Y-m-d') }}" required>
                        </label>
                        <input type="hidden" name="type" value="dwg">
                        <input type="hidden" name="issue" value="true">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-info btn-prev">
                            <svg class="bi bi-arrow-left" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M5.854 4.646a.5.5 0 0 1 0 .708L3.207 8l2.647 2.646a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 0 1 .708 0z"/>
                                <path fill-rule="evenodd" d="M2.5 8a.5.5 0 0 1 .5-.5h10.5a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
                            </svg>
                            Terug
                        </button>
                        <button type="submit" class="btn btn-info closeModal">
                            <svg class="bi bi-download" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M.5 8a.5.5 0 0 1 .5.5V12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V8.5a.5.5 0 0 1 1 0V12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V8.5A.5.5 0 0 1 .5 8z"/>
                                <path fill-rule="evenodd" d="M5 7.5a.5.5 0 0 1 .707 0L8 9.793 10.293 7.5a.5.5 0 1 1 .707.707l-2.646 2.647a.5.5 0 0 1-.708 0L5 8.207A.5.5 0 0 1 5 7.5z"/>
                                <path fill-rule="evenodd" d="M8 1a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-1 0v-8A.5.5 0 0 1 8 1z"/>
                            </svg>
                            Download
                        </button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Sluiten</button>
                    </div>
                </form> {# Datum input form #}
            </div>
        </div>
    </div>
{% endblock %}