src/Entity/Document.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DocumentRepository")
 * @Vich\Uploadable
 * @UniqueEntity(
 *     fields={"discipline", "building", "version", "documentType"},
 *     errorPath="location",
 *     message="Een document met deze bestandsnaam bestaat al"
 * )
 * UNIQUE ENTITY NEEMT FLOOR NIET IN BESCHOUWING. DIT IS EEN BUG IN SYMFONY. UNIQUEENTITY TRIGGERT NIET OP NULL VALUES.
 */
class Document
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     * @var string
     */
    private $file_name;

    /**
     * @Vich\UploadableField(mapping="documents", fileNameProperty="file_name")
     */
    private $file_content;

    /**
     * @Vich\UploadableField(mapping="pdf", fileNameProperty="pdf_filename")
     */
    private $pdf_file;

    /**
     * @ORM\Column(type="string", length=100)
     * @var string
     */
    private $pdf_filename;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Discipline", inversedBy="documents", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $discipline;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Area", inversedBy="documents")
     */
    private $area;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Building", inversedBy="documents")
     */
    private $building;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Location", inversedBy="documents")
     */
    private $location;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $floor;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\DocumentHistory", mappedBy="document")
     * @ORM\OrderBy({"revision" = "DESC"})
     */
    private $documentHistories;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\DocumentType", inversedBy="documents")
     * @ORM\JoinColumn(nullable=false)
     */
    private $documentType;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Issue", mappedBy="document", cascade={"persist", "remove"})
     */
    private $issue;

    /**
     * @ORM\Column(type="integer", nullable=false)
     */
    private $version;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\DocumentDraft", mappedBy="document")
     */
    private $documentDrafts;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     */
    private $uploadedBy;


    public function __construct()
    {
        $this->documentHistories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFileName(): ?string
    {
        return $this->file_name;
    }

    /**
     * Return filename without file extension
     * @return string
     */
    public function getDocumentName(): string
    {
        return substr($this->file_name, 0, -4);
    }

    public function setFileName(?string $file_name): self
    {
        $this->file_name = $file_name;

        return $this;
    }

    public function getPdfFilename()
    {
        return $this->pdf_filename;
    }

    public function setPdfFilename(?string $name)
    {
        $this->pdf_filename = $name;

        return $this;
    }

    public function getFileContent()
    {
        return $this->file_content;
    }

    public function setFileContent($file_content = null): void
    {
        $this->file_content = $file_content;

        if ($file_content) {
            $this->updated_at = new \DateTime('now');
        }
    }

    public function getPdfFile()
    {
        return $this->pdf_file;
    }

    public function setPdfFile($pdf_file = null): void
    {
        $this->pdf_file = $pdf_file;

        if ($pdf_file) {
            $this->updated_at = new \DateTime('now');
        }
    }

    public function getFloor(): ?string
    {
        return $this->floor;
    }

    public function setFloor(?string $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getDisciplineCode(): ?discipline
    {
        return $this->discipline;
    }

    public function setDisciplineCode(?discipline $discipline_code): self
    {
        $this->discipline = $discipline_code;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDiscipline(): ?Discipline
    {
        return $this->discipline;
    }

    public function setDiscipline(?Discipline $discipline): self
    {
        $this->discipline = $discipline;

        return $this;
    }

    /** Files only contain .pdf or .dwg, so slice last four characters */
    public function getFileType()
    {
        return substr($this->file_name, -4, 4);
    }

    public function __toString()
    {
        return $this->getFileName();
    }

    public function getArea(): ?Area
    {
        return $this->area;
    }

    public function setArea(?Area $area): self
    {
        $this->area = $area;

        return $this;
    }

    public function getBuilding(): ?Building
    {
        return $this->building;
    }

    public function setBuilding(?Building $building): self
    {
        $this->building = $building;

        return $this;
    }

    public function getLocation(): ?Location
    {
        return $this->location;
    }

    public function setLocation(?Location $location): self
    {
        $this->location = $location;

        return $this;
    }

    /**
     * @return Collection|DocumentHistory[]
     */
    public function getDocumentHistories(): Collection
    {
        return $this->documentHistories;
    }

    public function addDocumentHistory(DocumentHistory $documentHistory): self
    {
        if (!$this->documentHistories->contains($documentHistory)) {
            $this->documentHistories[] = $documentHistory;
            $documentHistory->setDocument($this);
        }

        return $this;
    }

    public function removeDocumentHistory(DocumentHistory $documentHistory): self
    {
        if ($this->documentHistories->contains($documentHistory)) {
            $this->documentHistories->removeElement($documentHistory);
            // set the owning side to null (unless already changed)
            if ($documentHistory->getDocument() === $this) {
                $documentHistory->setDocument(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|DocumentDraft[]
     */
    public function getDocumentDrafts(): Collection
    {
        return $this->documentDrafts;
    }

    public function addDocumentDrafts(DocumentDraft $documentDraft): self
    {
        if (!$this->documentDrafts->contains($documentDraft)) {
            $this->documentDrafts[] = $documentDraft;
            $documentDraft->setDocument($this);
        }

        return $this;
    }

    public function removeDocumentDrafts(DocumentDraft $documentDraft): self
    {
        if ($this->documentDrafts->contains($documentDraft)) {
            $this->documentDrafts->removeElement($documentDraft);
            // set the owning side to null (unless already changed)
            if ($documentDraft->getDocument() === $this) {
                $documentDraft->setDocument(null);
            }
        }

        return $this;
    }

    public function getDocumentType(): ?DocumentType
    {
        return $this->documentType;
    }

    public function setDocumentType(?DocumentType $documentType): self
    {
        $this->documentType = $documentType;

        return $this;
    }

    public function getIssue(): ?Issue
    {
        return $this->issue;
    }

    public function setIssue(Issue $issue): self
    {
        $this->issue = $issue;

        // set the owning side of the relation if necessary
        if ($issue->getDocument() !== $this) {
            $issue->setDocument($this);
        }

        return $this;
    }

    /**
     * @return integer
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * @param integer $version
     */
    public function setVersion($version): void
    {
        $this->version = $version;
    }

    public function getUploadedBy(): ?User
    {
        return $this->uploadedBy;
    }

    public function setUploadedBy(?User $uploadedBy): self
    {
        $this->uploadedBy = $uploadedBy;

        return $this;
    }
}

src/Entity/DocumentDraft.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * @ORM\Entity(repositoryClass="App\Repository\DocumentDraftRepository")
 * @Vich\Uploadable
 */
class DocumentDraft
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Document", inversedBy="documentDrafts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $document;

    /**
     * @ORM\Column(type="string", length=100)
     * @var string
     */
    private $file_name;

    /**
     * @Vich\UploadableField(mapping="drafts", fileNameProperty="file_name")
     */
    private $file_content;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="documentDrafts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $uploaded_by;

    /**
     * @ORM\Column(type="datetime")
     */
    private $uploaded_at;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $rejection_description;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $changed_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\DraftStatus", inversedBy="draft")
     * @ORM\JoinColumn(nullable=false)
     */
    private $draftStatus;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFileName(): ?string
    {
        return $this->file_name;
    }

    public function setFileName(?string $file_name): self
    {
        $this->file_name = $file_name;

        return $this;
    }

    public function getDocument(): ?Document
    {
        return $this->document;
    }

    public function setDocument(?Document $document): self
    {
        $this->document = $document;

        return $this;
    }

    public function getFileContent()
    {
        return $this->file_content;
    }

    public function setFileContent($file_content = null): void
    {
        $this->file_content = $file_content;

        if ($file_content) {
            $this->uploaded_at = new \DateTime('now');
        }
    }

    public function getUploadedBy(): ?User
    {
        return $this->uploaded_by;
    }

    public function setUploadedBy(?User $uploaded_by): self
    {
        $this->uploaded_by = $uploaded_by;

        return $this;
    }

    public function getUploadedAt(): ?\DateTimeInterface
    {
        return $this->uploaded_at;
    }

    public function setUploadedAt(\DateTimeInterface $uploaded_at): self
    {
        $this->uploaded_at = $uploaded_at;

        return $this;
    }

    public function getRejectionDescription(): ?string
    {
        return $this->rejection_description;
    }

    public function setRejectionDescription(?string $rejection_description): self
    {
        $this->rejection_description = $rejection_description;

        return $this;
    }

    public function getChangedAt(): ?\DateTimeInterface
    {
        return $this->changed_at;
    }

    public function setChangedAt(?\DateTimeInterface $changed_at): self
    {
        $this->changed_at = $changed_at;

        return $this;
    }

    public function getDraftStatus(): ?DraftStatus
    {
        return $this->draftStatus;
    }

    public function setDraftStatus(?DraftStatus $draftStatus): self
    {
        $this->draftStatus = $draftStatus;

        return $this;
    }

    public function __toString()
    {
        return $this->getDocument()->getFileName();
    }
}

templates/drafts/admin/index.html.twig
{%  extends 'profile/settings.html.twig' %}

{% block content %}

    <div class="card">
        <div class="card_head">
            <h4>Geuploade concepten</h4>
        </div>
        <div class="card_body no-padding">
            {% if drafts is not defined or drafts is empty %}
                <h2 class="text-center">Geen openstaande concepten</h2>
            {% else %}
            <div id="listingContainer">
                <table class="table dataTable cell-border" id="uploaded_documents">
                    <thead>
                    <tr>
                        <th>STATUS</th>
                        <th>NAAM</th>
                        <th>DOOR</th>
                        <th>INGELEVERD</th>
                    </tr>
                    </thead>
                    <tbody>

                        {% for draft in drafts %}
                            <tr data-href="{{ path('draft.approve', {documentDraftId: draft.id}) }}" class="clickable-row">
                                <td>
                                    {% if draft.draftStatus.name == "Afgekeurd" %}
                                        <svg class="red bi bi-x-circle" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                            <path fill-rule="evenodd" d="M11.854 4.146a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708-.708l7-7a.5.5 0 0 1 .708 0z"/>
                                            <path fill-rule="evenodd" d="M4.146 4.146a.5.5 0 0 0 0 .708l7 7a.5.5 0 0 0 .708-.708l-7-7a.5.5 0 0 0-.708 0z"/>
                                        </svg>
                                        {{ draft.draftStatus.name }}

                                    {% elseif draft.draftStatus.name == "In behandeling" %}
                                        <svg class="bi bi-stopwatch" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" d="M8 15A6 6 0 1 0 8 3a6 6 0 0 0 0 12zm0 1A7 7 0 1 0 8 2a7 7 0 0 0 0 14z"/>
                                            <path fill-rule="evenodd" d="M8 4.5a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5H4.5a.5.5 0 0 1 0-1h3V5a.5.5 0 0 1 .5-.5zM5.5.5A.5.5 0 0 1 6 0h4a.5.5 0 0 1 0 1H6a.5.5 0 0 1-.5-.5z"/>
                                            <path d="M7 1h2v2H7V1z"/>
                                        </svg>
                                        {{ draft.draftStatus.name}}

                                    {% elseif draft.draftStatus.name == "Geaccepteerd" %}
                                        <svg class="green bi bi-check-circle" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                            <path fill-rule="evenodd" d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.236.236 0 0 1 .02-.022z"/>
                                        </svg>
                                        {{ draft.draftStatus.name }}
                                    {% endif %}
                                </td>
                                <td>{{ draft.document }}</td>
                                <td>{{ draft.uploadedBy }}</td>
                                <td>{{ draft.uploadedAt.format("d-m-Y H:m") }}</td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/drafts/admin/show.html.twig
{% extends 'profile/settings.html.twig' %}

{% block content %}
        <div class="card">
            <div class="card_head">
                <h4>Concept goedkeuren: {{ draft.document.documentName }}</h4>
            </div>
            <div class="card_body no-padding">
                <div class="pl-25">
                    <b>Download DWG</b>
                    <a class="downloadButtonContainer" href="{{ path('document.download', {documentId: draft.document.id, type: "DWG", issue: false}) }}">
                        <svg class="bi bi-file-earmark-arrow-down" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path d="M4 1h5v1H4a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V6h1v7a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2z"/>
                            <path d="M9 4.5V1l5 5h-3.5A1.5 1.5 0 0 1 9 4.5z"/>
                            <path fill-rule="evenodd" d="M5.646 9.146a.5.5 0 0 1 .708 0L8 10.793l1.646-1.647a.5.5 0 0 1 .708.708l-2 2a.5.5 0 0 1-.708 0l-2-2a.5.5 0 0 1 0-.708z"/>
                            <path fill-rule="evenodd" d="M8 6a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-1 0v-4A.5.5 0 0 1 8 6z"/>
                        </svg>
                    </a>
                </div>
                <hr>
                <table class="table table-borderless">
                    <tr>
                        <td>Geupload</td>
                        <td>{{ draft.uploadedAt.format("d-m-Y H:m") }}</td>
                    </tr>
                    <tr>
                        <td>Door</td>
                        <td>{{ draft.uploadedBy }}</td>
                    </tr>
                    <tr>
                        <td>Discipline</td>
                        <td>{{ draft.document.discipline }}</td>
                    </tr>
                    <tr>
                        <td>Document type</td>
                        <td>{{ draft.document.documentType }}</td>
                    </tr>
                    <tr>
                        <td>Organisatie</td>
                        <td>{{ draft.document.location.organisation }}</td>
                    </tr>
                    <tr>
                        <td>Locatie</td>
                        <td>{{ draft.document.location }}</td>
                    </tr>
                    <tr>
                        <td>Gebouw</td>
                        <td>{{ draft.document.building }}</td>
                    </tr>
                    <tr>
                        <td>Verdieping</td>
                        <td>{{ draft.document.floor }}</td>
                    </tr>
                    <tr>
                        <td>Gebouwdeel</td>
                        <td>{{ draft.document.area }}</td>
                    </tr>
                </table>
                <hr>
                <button class="btn btn-danger float-left ml-2" data-toggle="modal" data-target="#concept_afkeuren">
                    <svg class="text-white bi bi-x-circle" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                        <path fill-rule="evenodd" d="M11.854 4.146a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708-.708l7-7a.5.5 0 0 1 .708 0z"/>
                        <path fill-rule="evenodd" d="M4.146 4.146a.5.5 0 0 0 0 .708l7 7a.5.5 0 0 0 .708-.708l-7-7a.5.5 0 0 0-.708 0z"/>
                    </svg>
                    Concept afkeuren
                </button>
                <button class="btn btn-success float-right mr-2" data-toggle="modal" data-target="#concept_goedkeuren">
                    <svg class="bi bi-check-circle" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                        <path fill-rule="evenodd" d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.236.236 0 0 1 .02-.022z"/>
                    </svg>
                    Concept accepteren
                </button>
            </div>
        </div>

    {#  Afkeuren modal  #}
    <div class="modal fade" id="concept_afkeuren" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Concept afkeuren</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{ path('draft.deny', {id: draft.id}) }}" method="POST">
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="denyDescription">Reden voor afkeuren:</label>
                            <textarea class="form-control" id="denyDescription" name="denyDescription" rows="3" placeholder="Deze tekst wordt naar de gebruiker gemaild."></textarea>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-danger">Afkeuren</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    {#  goedkeuren modal  #}
    <div class="modal fade" id="concept_goedkeuren" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Concept goedkeuren</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {{ form_start(form) }}
                <div class="modal-body">
                        <div class="form-group">
                            {{ form_row(form.pdfFile) }}
                        </div>
                    </div>
                    <div class="modal-footer">
                        {{ form_row(form.submit) }}
                    </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}